### ISSUE TITLE
SVG icons are not displayed (AUR package)

### ISSUE THREAD

**Issue by bordam** [rafatosta/zapzap#157]
After installing through AUR, I get these messages. I know it's just a packaging issue since this problem doesn't occour in flatpak, but maybe you could help me getting this fixed.... Thanks!

![immagine](https://github.com/rafatosta/zapzap/assets/95233098/6cae24f5-935d-478a-996e-8c7ea938637e)

**Comment by rafatosta** [comment]
WHAT is not maintained or supported by me. So, I can't help you since I don't know what they're doing in this packaging.

**Comment by rafatosta** [comment]
You can try manual installation by downloading the source code and following the steps described in https://github.com/rafatosta/zapzap/issues/153#issuecomment-1570288198

**Comment by bordam** [comment]
I'm the AUR package maintainer. I was asking your help fixing the AUR package... you can view the PKGBUILD here

https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=zapzap

**Comment by rafatosta** [comment]
😅 No problem!

The error you're getting is because you're doing the installation the wrong way. 

Use setup.py to install. This file contains all the files and folders to be installed for the application.

See topic 4.2.
https://wiki.archlinux.org/title/Python_package_guidelines

You can ask if you can't. I say unsupported because users do so much on their system that it's hard for me, a non-arch user, to know what's been done 😅🤣

**Comment by rafatosta** [comment]
😅 No problem!

The error you're getting is because you're doing the installation the wrong way. 

Use setup.py to install. This file contains all the files and folders to be installed for the application.

See topic 4.2.
https://wiki.archlinux.org/title/Python_package_guidelines

You can ask if you can't. I say unsupported because users do so much on their system that it's hard for me, a non-arch user, to know what's been done 😅🤣

**Comment by bordam** [comment]
😂😂 don't worry

Unfortunately, even doing as described in 4.2 it doesn't work

**Comment by rafatosta** [comment]
What error appears now?

**Comment by rafatosta** [comment]
I remember that it worked through the AUR, did it stop out of nowhere or was it after some update of mine?

**Comment by rafatosta** [comment]
I remember that it worked through the AUR, did it stop out of nowhere or was it after some update of mine?

**Comment by rafatosta** [comment]
Do the following, manually copy these folders in the PKGBUILD

**Comment by bordam** [comment]
> I remember that it worked through the AUR, did it stop out of nowhere or was it after some update of mine?

I don't know, at some point it stopped working, no idea if it was an update from your side or an archlinux update

**Comment by bordam** [comment]
> Do the following, manually copy these folders in the PKGBUILD

Hmmm, what folders do you mean

**Comment by bordam** [comment]
Hmmm, actually those files already exist, they are part of this package

**Comment by rafatosta** [comment]
> Hmmm, actually those files already exist, they are part of this package

For these things I stopped using Arch. Simple things that stop working and that you have to spend an absurd amount of time trying to solve. 
Apparently it's easier to create a .sh that does the installation 😅

**Comment by rafatosta** [comment]
Zapzap was so buggy in Arch that I decided not to keep it in the AUR. Things that don't happen running locally or on the flatpak were happening and it didn't make any sense 🤣🤣

**Comment by bordam** [comment]
Yeah ikr 😂😂 for the moment I’ll just leave the package as it is and I’ll see if an arch update solves the issue 🤷‍♂️🤷‍♂️
