### ISSUE TITLE
unable to paste text from clipboard to chat

### ISSUE THREAD

**Issue by giantoid** [rafatosta/zapzap#166]
unable to paste text from clipboard to chat
[Screencast dari 2023-07-04 11-48-10.webm](https://github.com/rafatosta/zapzap/assets/86581304/17a67af2-e0df-447e-823b-204ae9566ba9)

**Comment by rafatosta** [comment]
Unfortunately this is a "problem" with gnome apps on Wayland.
I recommend switching to X11 via Flatseal
#162

**Comment by rafatosta** [comment]
To clarify, Zapzap uses PyQt, so some things take a while to arrive and not everything will have the same support as in Qt with C++. 
It's not a limitation of Python, but of the PyQt library which is maintained by [Riverbank](https://riverbankcomputing.com/software/pyqt/).

**Is it worth migrating to C++?**
*No. Because it's just a WebApp.*

**Is X11 outdated and insecure?**
*For Zapzap it makes no difference.*

**But I want to use Wayland, can I?**
*Yes. You are free to do this. But the limitations are not on the part of the dev. And contributions are always welcome.*

**Comment by rafatosta** [comment]
Solved
