### ISSUE TITLE
ZapZap hangs during start-up

### ISSUE THREAD

**Issue by joenepraat** [rafatosta/zapzap#191]
Since version 5.3.3 ZapZap hangs during start-up. It doesn't matter if I run it using the super-key or from command-line. If I uninstall ZapZap, incl. user configuration, it works once. But after closing and restarting ZapZap, it hangs again. This is the output on the command-line:

```
user:~$ flatpak run com.rtosta.zapzap 
F: Not sharing "/usr/share/themes" with sandbox: Path "/usr" is reserved by Flatpak
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/app/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/app/bin/qtwebengine_dictionaries'
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
js: Error with Permissions-Policy header: Feature xr-spatial-tracking's parameters are ignored.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
js: Error with Permissions-Policy header: Unrecognized feature: 'bluetooth'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage'.
js: Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'shared-storage-select-url'.
```

Ubuntu 24.04.

**Comment by rafatosta** [comment]
The problem is in your FlatPak installation and not on Zapzap!

As you can see, there is a flaw related to Qtwengine folder.

`F: Not sharing "/usr/share/themes" with sandbox: Path "/usr" is reserved by Flatpak
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/app/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/app/bin/qtwebengine_dictionaries'`

Try to install the zap zap or do the manual installation of the packets through:
`flatpak install flathub org.kde.Platform//6.7 org.kde.Sdk//6.7 com.riverbankcomputing.PyQt.BaseApp//6.7 `

Note: It is not a Zapzap problem. So look for Flatpak support.

**Comment by joenepraat** [comment]
It worked a few days ago. I installed those flatpak packages you are advising, but it didn't fixed the problem (but installed 1+ GB KDE packages). Same errors, also after re-login. So I'm going to try another solution. Thanks anyway.
