### ISSUE TITLE
Call/Video Call

### ISSUE THREAD

**Issue by sufiproz** [rafatosta/zapzap#199]
If its a desktop application why doesn't it have call/video call features like the WhatsApp Desktop application.

**Comment by rafatosta** [comment]
Hello, it doesn't have these features because it's not WhatsApp on Windows. It's just a Webapp with great integration with the Linux system.
Please read:
- https://github.com/rafatosta/zapzap/blob/main/README.md
- https://rtosta.com/zapzap-web/#home

**Comment by PranavBhattarai** [comment]
> It's just a Webapp with **great** integration with the Linux system.

That cracked me up. Nothing wrong, though. But I think, (I could be wrong) it would have been normal if you had said:
" It's just a Webapp with integration with the Linux system." 

 
@rafatosta 
I think since WhatsApp application is NOT a social application like TikTok, Facebook, etc. They are used for content creation. 
WhatsApp is a communication channel similar to Telegram, Viber, Messenger, etc. 

So, it's obvious for users to expect **call functionality** from a WhatsApp **alternative**, which is its primary feature.
It would have made a lot of sense if the **README** clearly mentioned what **NOT** to expect.
I have to search in the Issue to see if anyone had said something it regarding those main features.

If this feature is not possible to implement due to "web app" limitation or due to WhatsApp policy, then that information would have made sense for the user if there is any point in searching alternative to ZapZap. Since that 3rd party application would have the same limitations/problems that ZapZap currently has (unless it's doable in another application).

**Comment by rafatosta** [comment]
> > It's just a Webapp with **great** integration with the Linux system.
> 
> That cracked me up. Nothing wrong, though. But I think, (I could be wrong) it would have been normal if you had said: " It's just a Webapp with integration with the Linux system."
> 
> [@rafatosta](https://github.com/rafatosta) I think since WhatsApp application is NOT a social application like TikTok, Facebook, etc. They are used for content creation. WhatsApp is a communication channel similar to Telegram, Viber, Messenger, etc.
> 
> So, it's obvious for users to expect **call functionality** from a WhatsApp **alternative**, which is its primary feature. It would have made a lot of sense if the **README** clearly mentioned what **NOT** to expect. I have to search in the Issue to see if anyone had said something it regarding those main features.
> 
> If this feature is not possible to implement due to "web app" limitation or due to WhatsApp policy, then that information would have made sense for the user if there is any point in searching alternative to ZapZap. Since that 3rd party application would have the same limitations/problems that ZapZap currently has (unless it's doable in another application).

Unfortunately, not everyone reads and reasoning a little.

**Comment by PranavBhattarai** [comment]
> Unfortunately, not everyone reads and reasoning a little.

I mean, I can get it that you want users to install the app or at least try the app, before they uninstall it, because lack of call functionality. But assuming "not everyone reads" seems to me that you are downplaying the situation.

**Flatpak description** and **ReadMe** in GitHub; both are important **common** places for users who are nerdy enough to use Linux distros to read such vital information. I'm not talking about Windows users, where WhatsApp officially provides a Desktop installer. 

<img width="851" height="118" alt="Image" src="https://github.com/user-attachments/assets/e5ba142d-bdac-4557-8626-32e44e5f1649" />
