### ISSUE TITLE
Zapzap consumes 1.0GB of RAM

### ISSUE THREAD

**Issue by christiantosta** [rafatosta/zapzap#243]
The app is amazing, but that is a problem: it's consuming so much RAM on my Fedora 41 Desktop. 
Perhaps the Chromium part used by PyQt6WebEngine.

Keep a look at this as one alternative web engine: https://github.com/sailfishos/qtmozembed
Other alternative can be treat HTTP traffic with Python/C++ on the backend level and render the interface using Kirigami.

![image](https://github.com/user-attachments/assets/977b4089-4077-401a-8b03-0e11b6bbd273)

**Comment by rafatosta** [comment]
Memory use depends on the use and this is managed by WhatApp Web. Many conversations and interactions make cache increase to avoid locking and drop in messaging performance.

In addition to having relatively high consumption at the initial moments because of synchronization, regardless of whether or not it has ended.

 As I use only for exporadic messages, it does not consume that much.
![image](https://github.com/user-attachments/assets/32d000aa-731a-4dbf-b39e-8fdc28f8655d)

It is possible to limit the amount of RAM to be used by ZAPZAP, but I do not know the impact of this on daily use. A possible reduction will surely be well regarded by the "RAM worshipers", but will be unstable.

**Comment by rafatosta** [comment]
This practically prevents consumption increasing, but made Zapzap very slow. Anyway, maybe I put this option as customization and let the user's discretion activate or not.

![image](https://github.com/user-attachments/assets/a56d6a7f-ca6b-4faf-9890-da7fabe7db90)

**Comment by christiantosta** [comment]
In another machine with another account (sporadic messages), same occurs:

![image](https://github.com/user-attachments/assets/1a7f099b-3b87-401c-91dd-131d868d834d)

Same account on firefox tab:

![image](https://github.com/user-attachments/assets/2571bf0e-bfd4-427c-9b15-02d604fad8fb)

**Comment by rafatosta** [comment]
> In another machine with another account (sporadic messages), same occurs:
> 
> ![image](https://github.com/user-attachments/assets/1a7f099b-3b87-401c-91dd-131d868d834d)
> 
> Same account on firefox tab:
> 
> ![image](https://github.com/user-attachments/assets/2571bf0e-bfd4-427c-9b15-02d604fad8fb)
> 

Consumption is normal!

You compared a page with the full app running. Of course, the page will consume more memory. You need to consider everything that Firefox needs to execute to run Whatsapp Web. 

Not wanting to belittle your comment, but nowadays an app consuming 1Gb due to heavy use is not a problem.

I understand that for more modest machines this may interfere, but all of Zapzap's development was done on a modest machine, a 7th generation i5, RAM 12Gb that was 7 years old. If it works well for me, it will work well for most users.
