### ISSUE TITLE
Icon missing some DEs

### ISSUE THREAD

**Issue by supertrackster** [rafatosta/zapzap#8]
I'm on rocky linux with de mate. Zapzap installed with flatpack, the notification icon is not present, appears for a few seconds, then is replaced by a missing icon. Updated to the latest version but problem already existed before the update.
https://ibb.co/JdmmHGG

**Comment by rafatosta** [comment]
I am aware of this problem and have no idea what the cause is. The icon is dynamically loaded when a new notification arrives or the app loads.
I use gnome and it doesn't happen.
I will need more time to install other DE on VM to perform the tests by running the code locally and via flatpak.
Thank you very much for the feedback. =D

**Comment by rafatosta** [comment]
> I'm on rocky linux with de mate. Zapzap installed with flatpack, the notification icon is not present, appears for a few seconds, then is replaced by a missing icon. Updated to the latest version but problem already existed before the update. https://ibb.co/JdmmHGG

maybe the next update will solve this. If you can download and test directly running python as in the readme I would appreciate it.
