### ISSUE TITLE
Display issues with long caracter strings

### ISSUE THREAD

**Issue by rene-coty** [rafatosta/zapzap#96]
I recently added a complete French translation to the code, but now that I have updated to version 4.0 I noticed some display issues that are caused by long caracter strings (because the original strings in english always tend to be shorter than their French equivalents, it has always been so..).
As depicted in the screenshot below, long strings are truncated because the interface apparently doesn't adapt to their length.. (the 's' at the end of the translation of "User Management" doesn't appear, and the translation of the "New User" button is also truncated).
Is there a way to make the UI more adaptive, depending on the size of the translated strings ? That would ease the use by non-english users.. 
![Capture d’écran du 2022-08-20 21-50-03](https://user-images.githubusercontent.com/95506494/185764280-57f7f231-bd2e-4afa-8996-84087adea9a8.png)

**Comment by rafatosta** [comment]
Yes, it is possible.But we can have the freedom to translate the way you want it, it does not need to literally as I put it.
For example in Portuguese I only put "Usuários" for User Management because it gets too big and on the only "Novo" button.

![image](https://user-images.githubusercontent.com/18619894/185764794-1d1865bc-b1d2-47f0-97d1-18e820944ee2.png)

What I can suggest at the moment is to make the options shorter.But I will worry about the sizing in the next updates

**Comment by rene-coty** [comment]
OK then I will update the fr.po file, in the way you recommend
